###

GET http://localhost:3000/api/employees HTTP/1.1

###

POST http://localhost:3000/api/employees HTTP/1.1
Content-Type: application/json

{
    "name": "Vanessa Rebollo",
    "position": "Snr. Developer",
    "office": "Rome",
    "salary": "22000"
}

### 

GET http://localhost:3000/api/employees/674cf64163414551ece56798 HTTP/1.1

###

PUT http://localhost:3000/api/employees/674ced5791cf7715846b96a2
Content-Type: application/json

{
    "name": "Vanessa Carballo",
    "position": "Digital Marketing Manager",
    "office": "California",
    "salary": "20000"
}

###
DELETE http://localhost:3000/api/employees/674ced5791cf7715846b96a2
